# Site settings
title: Beekeeping Management System
description: Business Design Project - Data Modeling Assignment
baseurl: "/beekeeping-management-system" # the subpath of your site, e.g. /blog
url: "https://apsh2023.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# GitHub Pages safe mode
safe: true
highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Business Design Project.docx
  - README.md
  - DEPLOYMENT.md

# Collections
collections:
  sections:
    output: true
    permalink: /:collection/:name/

# Navigation
header_pages:
  - about.md
  - business-design.md
  - data-model.md